M48
; DRILL file {KiCad 8.0.5-8.0.5-0~ubuntu24.04.1} date 2024-10-01T20:33:59+0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-01T20:33:59+05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5-8.0.5-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X3.6264Y-4.1297
X3.8539Y-4.1297
M30
