M48
; DRILL file {KiCad 8.0.3-8.0.3-0~ubuntu24.04.1} date 2024-06-13T23:12:44+0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-06-13T23:12:44+05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3-8.0.3-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X3.6264Y-4.1494
X3.8539Y-4.1494
M30
